# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-deploy:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-modules-{{ checksum "package.json" }}
            - node-modules-

      - run: npm install

      - save_cache:
          key: node-modules-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: npm run build
      - run: npm run deploy

workflows:
  version: 2

  commit:
    jobs:
      - build-deploy:
          filters:
            branches:
              only: master
