// eslint-disable-next-line import/prefer-default-export
export const actionTypes = {
  LOAD_UNAVAILABILITIES_REQUEST: 'LOAD_UNAVAILABILITIES_REQUEST',
  REFRESH_UNAVAILABILITIES_REQUEST: 'REFRESH_UNAVAILABILITIES_REQUEST',
  UNAVAILABILITIES_REFRESHED_SUCCESS: 'UNAVAILABILITIES_REFRESHED_SUCCESS',
  UNAVAILABILITIES_RECEIVED_SUCCESS: 'UNAVAILABILITIES_RECEIVED_SUCCESS',
  UNAVAILABILITIES_RECEIVED_FAIL: 'UNAVAILABILITIES_RECEIVED_FAIL',
  UNAVAILABILITIES_REFRESHED_FAIL: 'UNAVAILABILITIES_REFRESHED_FAIL',
  CHANGE_DISPLAY_MODE: 'CHANGE_DISPLAY_MODE',
  CHANGE_CURRENT_AVAILABILITY: 'CHANGE_CURRENT_AVAILABILITY',
  RESET_CURRENT_AVAILABILITY: 'RESET_CURRENT_AVAILABILITY',

  REFERENTIEL_RECEIVED_SUCCESS: 'REFERENTIEL_RECEIVED_SUCCESS',
  REFERENTIEL_RECEIVED_FAIL: 'REFERENTIEL_RECEIVED_FAIL',
  LOAD_REFERENTIEL_REQUEST: 'LOAD_REFERENTIEL_REQUEST',

  LOAD_PRODUCTION_CATEGORIES_REQUEST: 'LOAD_PRODUCTION_CATEGORIES_REQUEST',
  PRODUCTION_CATEGORIES_RECEIVED_SUCCESS:
    'PRODUCTION_CATEGORIES_RECEIVED_SUCCESS',
  PRODUCTION_CATEGORIES_RECEIVED_FAIL: 'PRODUCTION_CATEGORIES_RECEIVED_FAIL',

  CHANGE_CURRENT_CATEGORY: 'CHANGE_CURRENT_CATEGORY',
  RESET_CURRENT_CATEGORY: 'RESET_CURRENT_CATEGORY',
};
