// eslint-disable-next-line import/prefer-default-export
export const actionTypes = {
  LOAD_UNAVAILABILITIES_REQUEST: 'LOAD_UNAVAILABILITIES_REQUEST',
  UNAVAILABILITIES_RECEIVED: 'UNAVAILABILITIES_RECEIVED',
  CHANGE_DISPLAY_TO_MAP: 'CHANGE_DISPLAY_TO_MAP',
};
