// eslint-disable-next-line import/prefer-default-export
export const actionTypes = {
  LOAD_UNAVAILABILITIES_REQUEST: 'LOAD_UNAVAILABILITIES_REQUEST',
  REFRESH_UNAVAILABILITIES_REQUEST: 'REFRESH_UNAVAILABILITIES_REQUEST',
  UNAVAILABILITIES_REFRESHED_SUCCESS: 'UNAVAILABILITIES_REFRESHED_SUCCESS',
  UNAVAILABILITIES_RECEIVED_SUCCESS: 'UNAVAILABILITIES_RECEIVED_SUCCESS',
  UNAVAILABILITIES_RECEIVED_FAIL: 'UNAVAILABILITIES_RECEIVED_FAIL',
  UNAVAILABILITIES_REFRESHED_FAIL: 'UNAVAILABILITIES_REFRESHED_FAIL',
  CHANGE_DISPLAY_TO_MAP: 'CHANGE_DISPLAY_TO_MAP',
  CHANGE_CURRENT_AVAILABILITY: 'CHANGE_CURRENT_AVAILABILITY',
  RESET_CURRENT_AVAILABILITY: 'RESET_CURRENT_AVAILABILITY',

  REFERENTIEL_RECEIVED_SUCCESS: 'REFERENTIEL_RECEIVED_SUCCESS',
  REFERENTIEL_RECEIVED_FAIL: 'REFERENTIEL_RECEIVED_FAIL',
  LOAD_REFERENTIEL_REQUEST: 'LOAD_REFERENTIEL_REQUEST',

  LOAD_PRODUCTION_TYPES_REQUEST: 'LOAD_PRODUCTION_TYPES_REQUEST',
  PRODUCTION_TYPES_RECEIVED_SUCCESS: 'PRODUCTION_TYPES_RECEIVED_SUCCESS',
  PRODUCTION_TYPES_RECEIVED_FAIL: 'PRODUCTION_TYPES_RECEIVED_FAIL',
};
